// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TRIMMS_PROJECT.Models
{
    public partial class AllocationType
    {
        public AllocationType()
        {
            Allocations = new HashSet<Allocation>();
        }

        public string AllocId { get; set; }
        public string AllocationType1 { get; set; }

        public virtual ICollection<Allocation> Allocations { get; set; }
    }
}