// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TRIMMS_PROJECT.Models
{
    public partial class ClientGroup
    {
        public ClientGroup()
        {
            Clients = new HashSet<Client>();
        }

        public string ClientGroupId { get; set; }
        public string ClientGroupName { get; set; }

        public virtual ICollection<Client> Clients { get; set; }
    }
}