// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TRIMMS_PROJECT.Models
{
    public partial class Country
    {
        public Country()
        {
            Currencies = new HashSet<Currency>();
            States = new HashSet<State>();
        }

        public string CountryId { get; set; }
        public string CountryName { get; set; }
        public string RegionId { get; set; }

        public virtual Region Region { get; set; }
        public virtual ICollection<Currency> Currencies { get; set; }
        public virtual ICollection<State> States { get; set; }
    }
}