// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TRIMMS_PROJECT.Models
{
    public partial class Currency
    {
        public Currency()
        {
            Roles = new HashSet<Role>();
        }

        public string CurrencyId { get; set; }
        public string CurrencySymbol { get; set; }
        public string CountryId { get; set; }

        public virtual Country Country { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}