// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TRIMMS_PROJECT.Models
{
    public partial class Employee
    {
        public string EmpId { get; set; }
        public string EmpName { get; set; }
        public string Designation { get; set; }
        public string Location { get; set; }
        public DateTime Doj { get; set; }
        public DateTime Lwd { get; set; }
        public string VerticalL2 { get; set; }
        public string EmailId { get; set; }
        public string RmEmpId { get; set; }
        public string Band { get; set; }
        public string Level { get; set; }

       
        public virtual Location LocationNavigation { get; set; }
        public virtual L2Table VerticalL2Navigation { get; set; }
    }
}