// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TRIMMS_PROJECT.Models
{
    public partial class Holiday
    {
        public string HolidayId { get; set; }
        public DateTime Date { get; set; }
        public string Occasion { get; set; }
        public string LocationId { get; set; }
        public string StateId { get; set; }

        public virtual Location Location { get; set; }
        public virtual State State { get; set; }
    }
}