// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TRIMMS_PROJECT.Models
{
    public partial class L0Table
    {
        public L0Table()
        {
            L1Tables = new HashSet<L1Table>();
        }

        public string DivisonL0Id { get; set; }
        public string DivisonL0Title { get; set; }

        public virtual ICollection<L1Table> L1Tables { get; set; }
    }
}