// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TRIMMS_PROJECT.Models
{
    public partial class L1Table
    {
        public L1Table()
        {
            L2Tables = new HashSet<L2Table>();
        }

        public string DivisonL1Id { get; set; }
        public string DivisonL1Title { get; set; }
        public string DivisonL0Id { get; set; }

        public virtual L0Table DivisonL0 { get; set; }
        public virtual ICollection<L2Table> L2Tables { get; set; }
    }
}