// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TRIMMS_PROJECT.Models
{
    public partial class L2Table
    {
        public L2Table()
        {
            Employees = new HashSet<Employee>();
        }

        public string DivisonL2Id { get; set; }
        public string DivisonL2Title { get; set; }
        public string DivisonL1Id { get; set; }

        public virtual L1Table DivisonL1 { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}