// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TRIMMS_PROJECT.Models
{
    public partial class Module
    {
        public Module()
        {
            Timesheets = new HashSet<Timesheet>();
        }

        public string ModuleId { get; set; }
        public string ProjectId { get; set; }

        public virtual Project Project { get; set; }
        public virtual ICollection<Timesheet> Timesheets { get; set; }
    }
}