// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TRIMMS_PROJECT.Models
{
    public partial class Project
    {
        public Project()
        {
            Allocations = new HashSet<Allocation>();
            Modules = new HashSet<Module>();
            Roles = new HashSet<Role>();
        }

        public string ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string ClientId { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public string Po { get; set; }
        public string Sow { get; set; }
        public string Msa { get; set; }
        public string RefCode { get; set; }
        public string EngagementType { get; set; }

        public virtual Client Client { get; set; }
        public virtual ProjectType EngagementTypeNavigation { get; set; }
        public virtual ICollection<Allocation> Allocations { get; set; }
        public virtual ICollection<Module> Modules { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}