// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TRIMMS_PROJECT.Models
{
    public partial class ProjectType
    {
        public ProjectType()
        {
            Projects = new HashSet<Project>();
        }

        public string ProjectTypeId { get; set; }
        public string ProjectType1 { get; set; }

        public virtual ICollection<Project> Projects { get; set; }
    }
}