// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TRIMMS_PROJECT.Models
{
    public partial class Role
    {
        public string RoleId { get; set; }
        public string ProjectId { get; set; }
        public string RoleTitle { get; set; }
        public string CurrencyId { get; set; }
        public string BillingType { get; set; }
        public decimal BillingRate { get; set; }
        public string OverTimeRate { get; set; }
        public string OverTimeUnit { get; set; }

        public virtual Currency Currency { get; set; }
        public virtual Project Project { get; set; }
    }
}