// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TRIMMS_PROJECT.Models
{
    public partial class State
    {
        public State()
        {
            Holidays = new HashSet<Holiday>();
            Locations = new HashSet<Location>();
        }

        public string StateId { get; set; }
        public string StateName { get; set; }
        public string CountryId { get; set; }

        public virtual Country Country { get; set; }
        public virtual ICollection<Holiday> Holidays { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
    }
}