// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TRIMMS_PROJECT.Models
{
    public partial class Task
    {
        public Task()
        {
            Timesheets = new HashSet<Timesheet>();
        }

        public string TaskId { get; set; }
        public string TaskName { get; set; }
        public string TaskAssignmentType { get; set; }

        public virtual ICollection<Timesheet> Timesheets { get; set; }
    }
}